blank_issues_enabled: true
contact_links:
  - name: Search existing issues
    url: https://github.com/clojure-emacs/clojure-mode/issues?q=is%3Aissue
    about: Please check if your issue has already been reported before opening a new one.
