name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.emacs-version == 'snapshot' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs-version: ['27.1', '28.2', '29.4', '30.1', 'snapshot']
        include:
          - os: macos-latest
            emacs-version: '29.4'
          - os: windows-latest
            emacs-version: '29.4'

    steps:
      - uses: actions/checkout@v4

      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: emacs-eldev/setup-eldev@v1

      - name: Run regression tests
        run: eldev -dtT -p test

      - name: Lint
        run: eldev lint -c

      - name: Check for byte-compilation errors
        run: eldev -dtT compile --warnings-as-errors
